"""Daily/weekly report generator — markdown summaries with trends."""

from datetime import datetime, timezone
from typing import List, Optional

from .models.session import Session
from .models.stats import DashboardStats
from .pricing import estimate_cost, format_cost


def generate_markdown_report(
    sessions: List[Session],
    summary: DashboardStats,
    period: str = "daily",
) -> str:
    """Generate a markdown report."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    period_label = {"daily": "Daily", "weekly": "Weekly", "monthly": "Monthly"}.get(period, period.title())

    lines = [
        f"# \U0001fac0 Agent Pulse {period_label} Report",
        "",
        f"**Generated:** {now}",
        f"**Period:** Last {period}",
        "",
        "---",
        "",
        "## \U0001f4ca Overview",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| \U0001f4e6 Sessions | {summary.session_count} |",
        f"| \U0001f524 Tokens | {summary.tokens_display} |",
        f"| \U0001f527 Tool Calls | {summary.total_tool_calls} |",
        f"| \u23f1\ufe0f Duration | {summary.duration_display} |",
        f"| \U0001f4b0 Cost | {summary.cost_display} |",
        "",
    ]

    # Model breakdown
    if summary.model_breakdown:
        lines.extend([
            "## \U0001f916 Models Used",
            "",
            "| Model | Sessions | % |",
            "|-------|----------|---|",
        ])
        for model, count in sorted(summary.model_breakdown.items(), key=lambda x: -x[1]):
            pct = (count / summary.session_count * 100) if summary.session_count > 0 else 0
            bar = "\u2588" * int(pct / 5) + "\u2591" * (20 - int(pct / 5))
            lines.append(f"| {model[:25]} | {count} | {pct:.0f}% {bar} |")
        lines.append("")

    # Source breakdown
    if summary.source_breakdown:
        lines.extend([
            "## \U0001f4e1 Sources",
            "",
            "| Source | Sessions |",
            "|--------|----------|",
        ])
        for source, count in sorted(summary.source_breakdown.items(), key=lambda x: -x[1]):
            emoji = {"cli": "\U0001f4bb", "cron": "\u23f0", "weixin": "\U0001f4ac", "web": "\U0001f310"}.get(source, "\U0001f4cc")
            lines.append(f"| {emoji} {source} | {count} |")
        lines.append("")

    # Top sessions
    if sessions:
        lines.extend([
            "## \U0001f527 Top Sessions",
            "",
            "| # | Session | Model | Tokens | Tools | Cost |",
            "|---|---------|-------|--------|-------|------|",
        ])
        for i, s in enumerate(sessions[:10], 1):
            cost = estimate_cost(
                s.model, s.stats.input_tokens, s.stats.output_tokens,
                s.stats.cache_read_tokens, s.stats.cache_write_tokens,
            )
            lines.append(
                f"| {i} | {s.id[:20]} | {s.model[:18]} | "
                f"{_fmt_tokens(s.stats.total_tokens)} | {s.stats.tool_call_count} | {format_cost(cost)} |"
            )
        lines.append("")

    # Cost analysis
    if sessions:
        total_cost = sum(
            estimate_cost(s.model, s.stats.input_tokens, s.stats.output_tokens,
                         s.stats.cache_read_tokens, s.stats.cache_write_tokens)
            for s in sessions
        )
        avg_cost = total_cost / len(sessions) if sessions else 0
        lines.extend([
            "## \U0001f4b0 Cost Analysis",
            "",
            f"- **Total cost:** {format_cost(total_cost)}",
            f"- **Average per session:** {format_cost(avg_cost)}",
            f"- **Total tokens:** {summary.total_tokens:,}",
            "",
        ])

    lines.extend([
        "---",
        "",
        f"*Generated by [Agent Pulse](https://pypi.org/project/agent-pulse/) -- "
        f"`pip install agent-pulse`*",
    ])

    return "\n".join(lines)


def generate_terminal_report(console, sessions: List[Session], summary: DashboardStats, period: str = "daily") -> None:
    """Render a report summary in the terminal."""
    from rich.panel import Panel
    from rich.table import Table
    from rich.text import Text

    period_label = {"daily": "Daily", "weekly": "Weekly", "monthly": "Monthly"}.get(period, period.title())

    # Header
    console.print()
    console.print(f"  \U0001f4cb [bold cyan]{period_label} Report[/bold cyan]", highlight=False)
    console.print("\u2501" * console.width, style="dim blue")
    console.print()

    # Stats
    stats = Text()
    stats.append("  \U0001f4ca Sessions:  ", style="bold")
    stats.append(f"{summary.session_count}\n", style="cyan")
    stats.append("  \U0001f524 Tokens:    ", style="bold")
    stats.append(f"{summary.tokens_display}\n", style="magenta")
    stats.append("  \U0001f527 Tools:     ", style="bold")
    stats.append(f"{summary.total_tool_calls}\n", style="green")
    stats.append("  \u23f1\ufe0f Duration:  ", style="bold")
    stats.append(f"{summary.duration_display}\n", style="yellow")
    stats.append("  \U0001f4b0 Cost:      ", style="bold")
    stats.append(f"{summary.cost_display}\n", style="red")

    console.print(Panel(stats, title=f"\U0001f4ca {period_label} Summary", border_style="cyan", padding=(0, 2)))

    # Top sessions table
    if sessions:
        table = Table(title="\U0001f3c6 Top Sessions", border_style="dim", padding=(0, 1))
        table.add_column("#", style="dim", width=3)
        table.add_column("Session", style="cyan", max_width=20)
        table.add_column("Model", style="magenta", max_width=18)
        table.add_column("Tokens", justify="right", style="yellow")
        table.add_column("Tools", justify="right", style="green")
        table.add_column("Cost", justify="right", style="red")

        for i, s in enumerate(sessions[:10], 1):
            cost = estimate_cost(
                s.model, s.stats.input_tokens, s.stats.output_tokens,
                s.stats.cache_read_tokens, s.stats.cache_write_tokens,
            )
            table.add_row(
                str(i), s.id[:20], s.model[:18],
                _fmt_tokens(s.stats.total_tokens),
                str(s.stats.tool_call_count),
                format_cost(cost),
            )

        console.print()
        console.print(table)

    # Save prompt
    console.print()
    console.print(Panel(
        "  \U0001f4a1 Save report: [cyan]agent-pulse report --save report.md[/cyan]\n"
        "     Export HTML: [cyan]agent-pulse export-html -o report.html[/cyan]",
        title="\U0001f4be Export",
        border_style="dim",
        padding=(0, 2),
    ))


def _fmt_tokens(n: int) -> str:
    if n >= 1_000_000:
        return f"{n / 1_000_000:.1f}M"
    elif n >= 1_000:
        return f"{n / 1_000:.1f}K"
    return str(n)
